---

- name: docker python config
  pip:
    name: docker-py

- name: pull lacework image
  community.docker.docker_image:
   name: "{{ container.default_container_image }}"
   source: pull
 
- name: create default container
  community.docker.docker_container:
   name: "{{ container.default_container_name }}{{ item }}"
   image: "{{ container.default_container_image }}"
   command: "{{ container.default_container_command }}"
   state: present
  with_sequence: count="{{ container.container_counter }}"
